name: "Giraff Dashboard"
description: "A mobile-first, Scandinavian-minimal Home Assistant dashboard"
version: "1.0.7"
slug: "giraff"
url: "https://github.com/twinbolt-ab/giraff"
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 3000
panel_icon: "mdi:view-dashboard"
panel_title: "Giraff"
panel_admin: false
startup: "application"
init: false
